#ifndef AVR_GPIO_PINS
#define AVR_GPIO_PINS

const GPIO GPIO0  = GPIO(E,0);
const GPIO GPIO1  = GPIO(E,1);
const GPIO GPIO2  = GPIO(E,4);
const GPIO GPIO3  = GPIO(E,5);
const GPIO GPIO4  = GPIO(G,5);
const GPIO GPIO5  = GPIO(E,3);
const GPIO GPIO6  = GPIO(H,3);
const GPIO GPIO7  = GPIO(H,4);
const GPIO GPIO8  = GPIO(H,5);
const GPIO GPIO9  = GPIO(H,6);

const GPIO GPIO10 = GPIO(B,4);
const GPIO GPIO11 = GPIO(B,5);
const GPIO GPIO12 = GPIO(B,6);
const GPIO GPIO13 = GPIO(B,7);
const GPIO GPIO14 = GPIO(J,1);
const GPIO GPIO15 = GPIO(J,0);
const GPIO GPIO16 = GPIO(H,1);
const GPIO GPIO17 = GPIO(H,0);
const GPIO GPIO18 = GPIO(D,3);
const GPIO GPIO19 = GPIO(D,2);

const GPIO GPIO20 = GPIO(D,1);
const GPIO GPIO21 = GPIO(D,0);
const GPIO GPIO22 = GPIO(A,0);
const GPIO GPIO23 = GPIO(A,1);
const GPIO GPIO24 = GPIO(A,2);
const GPIO GPIO25 = GPIO(A,3);
const GPIO GPIO26 = GPIO(A,4);
const GPIO GPIO27 = GPIO(A,5);
const GPIO GPIO28 = GPIO(A,6);
const GPIO GPIO29 = GPIO(A,7);

const GPIO GPIO30 = GPIO(C,7);
const GPIO GPIO31 = GPIO(C,6);
const GPIO GPIO32 = GPIO(C,5);
const GPIO GPIO33 = GPIO(C,4);
const GPIO GPIO34 = GPIO(C,3);
const GPIO GPIO35 = GPIO(C,2);
const GPIO GPIO36 = GPIO(C,1);
const GPIO GPIO37 = GPIO(C,0);
const GPIO GPIO38 = GPIO(D,7);
const GPIO GPIO39 = GPIO(G,2);

const GPIO GPIO40 = GPIO(G,1);
const GPIO GPIO41 = GPIO(G,0);
const GPIO GPIO42 = GPIO(L,7);
const GPIO GPIO43 = GPIO(L,6);
const GPIO GPIO44 = GPIO(L,5);
const GPIO GPIO45 = GPIO(L,4);
const GPIO GPIO46 = GPIO(L,3);
const GPIO GPIO47 = GPIO(L,2);
const GPIO GPIO48 = GPIO(L,1);
const GPIO GPIO49 = GPIO(L,0);

const GPIO GPIO50 = GPIO(B,3);
const GPIO GPIO51 = GPIO(B,2);
const GPIO GPIO52 = GPIO(B,1);
const GPIO GPIO53 = GPIO(B,0);

#endif
